[package]
name = "relay-core-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "High-performance Rust traffic interception engine and proxy platform"

[features]
default = ["script", "transparent-linux", "transparent-macos"]
script = ["dep:relay-core-script"]
transparent-linux = ["relay-core-lib/transparent-linux"]
transparent-macos = ["relay-core-lib/transparent-macos"]

[dependencies]
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
tracing = "0.1"
log = "0.4"
futures = "0.3"
regex = "1.0"
lru = "0.16.3"

relay-core-api = { path = "../relay-core-api", version = "0.9.0" }
url.workspace = true
relay-core-lib = { path = "../relay-core-lib", version = "0.9.0", default-features = false }
relay-core-storage = { path = "../relay-core-storage", version = "0.9.0" }
relay-core-script = { path = "../relay-core-script", version = "0.9.0", optional = true }
async-trait = "0.1.89"

[dev-dependencies]
chrono = { workspace = true }
url = { workspace = true }
